CREATE TABLE oil_statistics.boiler_daily_statistics (
    bds SERIAL NOT NULL PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    btu numeric,
    kwh numeric,
    cycles integer,
    total_boiler_runtime numeric,
    avg_boiler_runtime numeric,
    min_boiler_runtime numeric,
    max_boiler_runtime numeric, 
    total_circulator_runtime numeric,
    avg_circulator_runtime numeric,
    min_circulator_runtime numeric,
    max_circulator_runtime numeric,
    total_zone1_time numeric,
    avg_zone1_time numeric,
    min_zone1_time numeric,
    max_zone1_time numeric,
    total_zone2_time numeric,
    avg_zone2_time numeric,
    min_zone2_time numeric,
    max_zone2_time numeric,
    total_zone3_time numeric,
    avg_zone3_time numeric,
    min_zone3_time numeric,
    max_zone3_time numeric,
    total_zone4_time numeric,
    avg_zone4_time numeric,
    min_zone4_time numeric,
    max_zone4_time numeric,
    total_zone5_time numeric,
    avg_zone5_time numeric,
    min_zone5_time numeric,
    max_zone5_time numeric,
    total_hot_water_time numeric,
    avg_hot_water_time numeric,
    min_hot_water_time numeric,
    max_hot_water_time numeric,
    updated timestamp with time zone
);
